# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 675)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 641, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ordersTable = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.ordersTable.setColumnCount(7)
        self.ordersTable.setObjectName("ordersTable")
        self.ordersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.ordersTable)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(730, 130, 381, 203))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.createConsumerButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.createConsumerButton.setObjectName("createConsumerButton")
        self.horizontalLayout_3.addWidget(self.createConsumerButton)
        self.nameCreateConsumerTF = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.nameCreateConsumerTF.setObjectName("nameCreateConsumerTF")
        self.horizontalLayout_3.addWidget(self.nameCreateConsumerTF)
        self.addressCreateConsumerTF = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.addressCreateConsumerTF.setObjectName("addressCreateConsumerTF")
        self.horizontalLayout_3.addWidget(self.addressCreateConsumerTF)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.consumersTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.consumersTable.setColumnCount(3)
        self.consumersTable.setObjectName("consumersTable")
        self.consumersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.consumersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.consumersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.consumersTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.consumersTable)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(730, 420, 381, 194))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.createDetailButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.createDetailButton.setObjectName("createDetailButton")
        self.horizontalLayout_4.addWidget(self.createDetailButton)
        self.nameDetailCreateTF = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.nameDetailCreateTF.setObjectName("nameDetailCreateTF")
        self.horizontalLayout_4.addWidget(self.nameDetailCreateTF)
        self.priceDetailCreateTF = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.priceDetailCreateTF.setObjectName("priceDetailCreateTF")
        self.horizontalLayout_4.addWidget(self.priceDetailCreateTF)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.detailsTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.detailsTable.setRowCount(0)
        self.detailsTable.setColumnCount(3)
        self.detailsTable.setObjectName("detailsTable")
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.detailsTable.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.detailsTable)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(730, 50, 228, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.consumerSearchTF = QtWidgets.QLineEdit(self.layoutWidget)
        self.consumerSearchTF.setObjectName("consumerSearchTF")
        self.verticalLayout_5.addWidget(self.consumerSearchTF)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.deleteConsumerButton = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteConsumerButton.setObjectName("deleteConsumerButton")
        self.horizontalLayout_5.addWidget(self.deleteConsumerButton)
        self.searchConsumerButton = QtWidgets.QPushButton(self.layoutWidget)
        self.searchConsumerButton.setObjectName("searchConsumerButton")
        self.horizontalLayout_5.addWidget(self.searchConsumerButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(730, 340, 228, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.detaiSearchTF = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.detaiSearchTF.setObjectName("detaiSearchTF")
        self.verticalLayout_6.addWidget(self.detaiSearchTF)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.deleteDetailButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.deleteDetailButton.setObjectName("deleteDetailButton")
        self.horizontalLayout_6.addWidget(self.deleteDetailButton)
        self.searchDetailButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.searchDetailButton.setObjectName("searchDetailButton")
        self.horizontalLayout_6.addWidget(self.searchDetailButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(980, 60, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(980, 350, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(690, -20, 20, 671))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 228, 77))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderSearchTF = QtWidgets.QLineEdit(self.layoutWidget1)
        self.orderSearchTF.setObjectName("orderSearchTF")
        self.verticalLayout_2.addWidget(self.orderSearchTF)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.orderDeleteButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.orderDeleteButton.setCheckable(False)
        self.orderDeleteButton.setDefault(False)
        self.orderDeleteButton.setFlat(False)
        self.orderDeleteButton.setObjectName("orderDeleteButton")
        self.horizontalLayout_2.addWidget(self.orderDeleteButton)
        self.orderSearchButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.orderSearchButton.setObjectName("orderSearchButton")
        self.horizontalLayout_2.addWidget(self.orderSearchButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(270, 50, 381, 111))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.purchaseDateCreateOrderDT = QtWidgets.QDateTimeEdit(self.layoutWidget2)
        self.purchaseDateCreateOrderDT.setReadOnly(False)
        self.purchaseDateCreateOrderDT.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1970, 1, 1), QtCore.QTime(0, 0, 0)))
        self.purchaseDateCreateOrderDT.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.purchaseDateCreateOrderDT.setCalendarPopup(True)
        self.purchaseDateCreateOrderDT.setObjectName("purchaseDateCreateOrderDT")
        self.gridLayout.addWidget(self.purchaseDateCreateOrderDT, 0, 1, 1, 1)
        self.qunatityCreateOrderTF = QtWidgets.QLineEdit(self.layoutWidget2)
        self.qunatityCreateOrderTF.setObjectName("qunatityCreateOrderTF")
        self.gridLayout.addWidget(self.qunatityCreateOrderTF, 1, 1, 1, 1)
        self.consumerIdCreateOrderTF = QtWidgets.QLineEdit(self.layoutWidget2)
        self.consumerIdCreateOrderTF.setObjectName("consumerIdCreateOrderTF")
        self.gridLayout.addWidget(self.consumerIdCreateOrderTF, 0, 0, 1, 1)
        self.detailIdCreateOrderTF = QtWidgets.QLineEdit(self.layoutWidget2)
        self.detailIdCreateOrderTF.setObjectName("detailIdCreateOrderTF")
        self.gridLayout.addWidget(self.detailIdCreateOrderTF, 1, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.createOrderButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.createOrderButton.setObjectName("createOrderButton")
        self.verticalLayout_7.addWidget(self.createOrderButton)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(700, 329, 460, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.useCurrentDateCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.useCurrentDateCheckBox.setGeometry(QtCore.QRect(470, 30, 131, 20))
        self.useCurrentDateCheckBox.setObjectName("useCurrentDateCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 22))
        self.menubar.setObjectName("menubar")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        self.menuRefresh = QtWidgets.QMenu(self.menubar)
        self.menuRefresh.setObjectName("menuRefresh")
        self.menuConnection = QtWidgets.QMenu(self.menubar)
        self.menuConnection.setObjectName("menuConnection")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_Orders = QtWidgets.QAction(MainWindow)
        self.actionClear_Orders.setObjectName("actionClear_Orders")
        self.actionClear_Consumers = QtWidgets.QAction(MainWindow)
        self.actionClear_Consumers.setObjectName("actionClear_Consumers")
        self.actionClear_Details = QtWidgets.QAction(MainWindow)
        self.actionClear_Details.setObjectName("actionClear_Details")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionRefresh_Orders = QtWidgets.QAction(MainWindow)
        self.actionRefresh_Orders.setObjectName("actionRefresh_Orders")
        self.actionRefresh_Consumers = QtWidgets.QAction(MainWindow)
        self.actionRefresh_Consumers.setObjectName("actionRefresh_Consumers")
        self.actionRefresh_Details = QtWidgets.QAction(MainWindow)
        self.actionRefresh_Details.setObjectName("actionRefresh_Details")
        self.actionRefresh_All = QtWidgets.QAction(MainWindow)
        self.actionRefresh_All.setObjectName("actionRefresh_All")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.menuTable.addAction(self.actionClear_Orders)
        self.menuTable.addAction(self.actionClear_Consumers)
        self.menuTable.addAction(self.actionClear_Details)
        self.menuTable.addAction(self.actionClear_All)
        self.menuRefresh.addAction(self.actionRefresh_Orders)
        self.menuRefresh.addAction(self.actionRefresh_Consumers)
        self.menuRefresh.addAction(self.actionRefresh_Details)
        self.menuRefresh.addAction(self.actionRefresh_All)
        self.menuConnection.addAction(self.actionConnect)
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuRefresh.menuAction())
        self.menubar.addAction(self.menuConnection.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.ordersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.ordersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Purchsae Date"))
        item = self.ordersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Consumer Id"))
        item = self.ordersTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Detail Id"))
        item = self.ordersTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Qunatity"))
        item = self.ordersTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Price"))
        self.createConsumerButton.setText(_translate("MainWindow", "Create"))
        self.nameCreateConsumerTF.setPlaceholderText(_translate("MainWindow", "Name"))
        self.addressCreateConsumerTF.setPlaceholderText(_translate("MainWindow", "Address"))
        item = self.consumersTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.consumersTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.consumersTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Address"))
        self.createDetailButton.setText(_translate("MainWindow", "Create"))
        self.nameDetailCreateTF.setPlaceholderText(_translate("MainWindow", "Name"))
        self.priceDetailCreateTF.setPlaceholderText(_translate("MainWindow", "Detail Price"))
        item = self.detailsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.detailsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.detailsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        self.consumerSearchTF.setPlaceholderText(_translate("MainWindow", "Consumer Name"))
        self.deleteConsumerButton.setText(_translate("MainWindow", "Delete"))
        self.searchConsumerButton.setText(_translate("MainWindow", "Search"))
        self.detaiSearchTF.setPlaceholderText(_translate("MainWindow", "Detail Name"))
        self.deleteDetailButton.setText(_translate("MainWindow", "Delete"))
        self.searchDetailButton.setText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Consumers"))
        self.label_2.setText(_translate("MainWindow", "Details"))
        self.orderSearchTF.setPlaceholderText(_translate("MainWindow", "Detail name or Consumer name"))
        self.orderDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.orderSearchButton.setText(_translate("MainWindow", "Search"))
        self.qunatityCreateOrderTF.setPlaceholderText(_translate("MainWindow", "Quantity"))
        self.consumerIdCreateOrderTF.setPlaceholderText(_translate("MainWindow", "Consumer ID"))
        self.detailIdCreateOrderTF.setPlaceholderText(_translate("MainWindow", "Detail ID"))
        self.createOrderButton.setText(_translate("MainWindow", "Create Record"))
        self.useCurrentDateCheckBox.setText(_translate("MainWindow", "Use current date"))
        self.menuTable.setTitle(_translate("MainWindow", "Table"))
        self.menuRefresh.setTitle(_translate("MainWindow", "Refresh"))
        self.menuConnection.setTitle(_translate("MainWindow", "Connection"))
        self.actionClear_Orders.setText(_translate("MainWindow", "Clear Orders"))
        self.actionClear_Consumers.setText(_translate("MainWindow", "Clear Consumers"))
        self.actionClear_Details.setText(_translate("MainWindow", "Clear Details"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))
        self.actionRefresh_Orders.setText(_translate("MainWindow", "Refresh Orders"))
        self.actionRefresh_Consumers.setText(_translate("MainWindow", "Refresh Consumers"))
        self.actionRefresh_Details.setText(_translate("MainWindow", "Refresh Details"))
        self.actionRefresh_All.setText(_translate("MainWindow", "Refresh All"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
